name: Set issues with a PR to In Progress (From PR)
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - labeled


jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: log all the context
        uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(github.context.payload, null, 2))