name: From Issues

on:
  issues:
    types:
      - edited
      - labeled


jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: log all the context
        uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(github.context, null, 2))
